version: "3"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    command: sh -c "./scripts/docker-entrypoint.sh"
    volumes:
      - .:/usr/src/app
